    const products = [{
      "id": "101",
      "title": "Medalla Galaxy",
      "price": 1490,
      "pictureUrl": "https://www.tegopet.com.ar/img/universe.jpg",
      "detail": "Nuestra medalla inteligente te permite cargar todos los datos de mascota en un solo lugar. Carga su foto, historia medica y tus datos de contacto por si algun dia se pierde",
      "stock" : 10,
      "initial" : 1,
      "idcategory": "Medallas",
    },
    {
      "id": "102",
      "title": "Medalla Black Bone",
      "price": 1490,
      "pictureUrl": "https://www.tegopet.com.ar/img/black-bone.jpg",
      "detail": "Nuestra medalla inteligente te permite cargar todos los datos de mascota en un solo lugar. Carga su foto, historia medica y tus datos de contacto por si algun dia se pierde",
      "stock" : 10,
      "initial" : 1,
      "idcategory": "Medallas",
    },
    {
      "id": "103",
      "title": "Medalla Cute Girl",
      "price": 1490,
      "pictureUrl": "https://www.tegopet.com.ar/img/cool-girl.jpg",
      "detail": "Nuestra medalla inteligente te permite cargar todos los datos de mascota en un solo lugar. Carga su foto, historia medica y tus datos de contacto por si algun dia se pierde",
      "stock" : 10,
      "initial" : 1,
      "idcategory": "Medallas",
    },
    {
      "id": "104",
      "title": "Medalla Navy Paw",
      "price": 1490,
      "pictureUrl": "https://www.tegopet.com.ar/img/navy-paw.jpg",
      "detail": "Nuestra medalla inteligente te permite cargar todos los datos de mascota en un solo lugar. Carga su foto, historia medica y tus datos de contacto por si algun dia se pierde",
      "stock" : 10,
      "initial" : 1,
      "idcategory": "Medallas",
    },
    {
      "id": "201",
      "title": "Collar Pink",
      "price": 2600,
      "pictureUrl": "https://cdn-sa-ec.yottaa.net/609426b74f1bbfff95ac5a83/es.pandora.net/v~4b.16/dw/image/v2/BFCR_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw1b29343c/images/productimages/main/312262C02_RGB.jpg?sw=900&sh=900&sm=fit&sfrm=png&bgcolor=F5F5F5&yocs=9_e_",
      "detail": "Nuestra medalla inteligente te permite cargar todos los datos de mascota en un solo lugar. Carga su foto, historia medica y tus datos de contacto por si algun dia se pierde",
      "stock" : 10,
      "initial" : 1,
      "idcategory": "Collares",
    },
  
  ]

    export default products